name: 'Build .NET'
description: 'Build .NET for Umbraco V8'
inputs:
  organization-name:
    required: true
  project-name:
    required: true
  build-configuration:
    required: true
    default: 'release'
  csproj-path:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Create Build Directory
      run: New-Item -Path .\_build -ItemType Directory -Force
      shell: powershell

    # - name : Setup nuget
    #   uses: nuget/setup-nuget@v1.0.6

    # - name: Restore nuget packages
    #   run: nuget restore Axendo.Umb.DataExpert.Platform.sln
    #   shell: powershell

    - name: Restore nuget packages
      run:  msbuild Axendo.Umb.DataExpert.Platform.sln /t:restore /p:RestoreAdditionalProjectSources="https://nuget.axendo.nl/"
      shell: powershell

    - name: Build Solution
      run: msbuild Axendo.Umb.DataExpert.Platform.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="_build"
      shell: powershell
   
    #- name: Build app
    #  run: msbuild ${{ inputs.csproj-path }} -t:rebuild -verbosity:diag -property:Configuration=${{ inputs.build-configuration }}

    # - name: Restore dependencies
    #   run: dotnet restore
    #   shell: powershell
      
    # - name: Build
    #   run: dotnet build --configuration ${{ inputs.build-configuration }}
    #   shell: powershell

    # - name: Stop AppPool and Website in IIS
    #   run: c:\.\DeploymentScripts\StopIISAppPool.ps1 "${{ inputs.organization-name }} ${{ inputs.project-name }} (${{ github.ref_name }})"
    #   shell: powershell
    
    # - name: Publish
    #   run: dotnet publish "${{ inputs.csproj-path }}" --output "/Sites/${{ inputs.organization-name }}/${{ inputs.project-name }}/${{ github.ref_name }}" --configuration ${{ inputs.build-configuration }} /p:EnvironmentName=Production --no-restore --no-build
    #   shell: powershell

    # - name: Create AppPool and Website in IIS
    #   run: C:\.\DeploymentScripts\CreateIISAppPoolAndWebsite.ps1 "${{ inputs.organization-name }} ${{ inputs.project-name }} (${{ github.ref_name }})" "${{ github.ref_name }}.${{ inputs.project-name }}.${{ inputs.organization-name }}" "C:\Sites\${{ inputs.organization-name }}\${{ inputs.project-name }}\${{ github.ref_name }}"
    #   shell: powershell