name: 'Build .NET'
description: 'Build .NET for Umbraco V8'
inputs:
  organization-name:
    required: true
  project-name:
    required: true
  build-configuration:
    required: true
    default: 'release'
  csproj-path:
    required: true
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Add GitHub PAT to nuget.config
      run: (Get-Content -path .\NuGet.config -Raw) -replace '{PAT}','${{ inputs.token }}' | Set-Content -Path .\NuGet.config
      shell: powershell

    - name : Setup Nuget
      uses: nuget/setup-nuget@v1.0.6

    - name: Restore nuget packages
      run: nuget restore ${{ inputs.csproj-path }}
      shell: powershell

    - name: Stop AppPool and Website in IIS
      run: c:\.\DeploymentScripts\StopIISAppPool.ps1 "${{ inputs.organization-name }} ${{ inputs.project-name }} (${{ github.ref_name }})"
      shell: powershell

    - name: Transform web.config
      run: |
        $webFolderExists = Test-Path .\*.web\
        if($webFolderExists){ cd .\*.web\ } else { cd .\*.site\ }
        $webBambooConfigExists = Test-Path web.bamboo.config
        if($webBambooConfigExists) {c:\.\DeploymentScripts\ConfigTransformationTool\ctt.exe s:web.config t:web.bamboo.config d:web.config pw}
      shell: powershell

    - name: Build Solution
      run: msbuild ${{ inputs.csproj-path }} /nologo /nr:false /p:DeployOnBuild=true /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:AutoParameterizationWebConfigConnectionStrings=false /p:MvcBuildViews=false
      shell: powershell
    
    - name: Create robots.txt (disallow all)
      run: |
        New-Item robots.txt -Force
        Set-Content robots.txt "User-agent: *`r`Disallow: /"
      shell: powershell

    - name: Copy files to sites folder
      run: |
        md -Force C:\Sites\${{ inputs.organization-name }}\${{ inputs.project-name }}\${{ github.ref_name }}
         $webFolderExists = Test-Path .\*.web\
         if($webFolderExists){Copy-Item .\*.Web\* C:\Sites\${{ inputs.organization-name }}\${{ inputs.project-name }}\${{ github.ref_name }} -force -recurse}
         if(-not $webFolderExists){Copy-Item .\*.Site\* C:\Sites\${{ inputs.organization-name }}\${{ inputs.project-name }}\${{ github.ref_name }} -force -recurse}
      shell: powershell
    
    - name: Create AppPool and Website in IIS
      run: C:\.\DeploymentScripts\CreateIISAppPoolAndWebsite.ps1 "${{ inputs.organization-name }} ${{ inputs.project-name }} (${{ github.ref_name }})" "${{ github.ref_name }}.${{ inputs.project-name }}.${{ inputs.organization-name }}" "C:\Sites\${{ inputs.organization-name }}\${{ inputs.project-name }}\${{ github.ref_name }}" "v4.0"
      shell: powershell
