name: 'Build .NET'
description: 'Build .NET for Umbraco V8'
inputs:
  organization-name:
    required: true
  project-name:
    required: true
  build-configuration:
    required: true
    default: 'release'
  csproj-path:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name : Setup Nuget
      uses: nuget/setup-nuget@v1.0.6

    - name: Restore nuget packages
      run: nuget restore Axendo.Umb.DataExpert.Platform.sln
      shell: powershell

    - name: Stop AppPool and Website in IIS
      run: c:\.\DeploymentScripts\StopIISAppPool.ps1 "${{ inputs.organization-name }} ${{ inputs.project-name }} (${{ github.ref_name }})"
      shell: powershell

    #config transform
    - name: Transform web.config
      run: c:\.\DeploymentScripts\ConfigTransformationTool\ctt.exe s:web.config t:web.bamboo.config d:web.test.config pw
      shell: powershell
      working-directory: Axendo.Umb.DataExpert.Platform.web

    - name: Build Solution
      run: msbuild Axendo.Umb.DataExpert.Platform.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:AutoParameterizationWebConfigConnectionStrings=false /p:MvcBuildViews=false
      shell: powershell

    # copy files to sites folder
    # create robots.txt (disallow all)
    # CreateAppPool CLR V

    - name: Create AppPool and Website in IIS
      run: C:\.\DeploymentScripts\CreateIISAppPoolAndWebsite.ps1 "${{ inputs.organization-name }} ${{ inputs.project-name }} (${{ github.ref_name }})" "${{ github.ref_name }}.${{ inputs.project-name }}.${{ inputs.organization-name }}" "C:\Sites\${{ inputs.organization-name }}\${{ inputs.project-name }}\${{ github.ref_name }}" "v4.0"
      shell: powershell


#      run: msbuild Axendo.Umb.DataExpert.Platform.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:OutDir="/Sites/${{ inputs.organization-name }}/${{ inputs.project-name }}/${{ github.ref_name }}" /p:AutoParameterizationWebConfigConnectionStrings=false /p:MvcBuildViews=false

# -source:contentPath="${bamboo.build.working.directory}\" 
# -dest:contentPath="${bamboo.DeployServerRoot}${bamboo.CustomerName}\${bamboo.ProjectName}\${bamboo.planRepository.branchName}\" 
# -skip:skipAction=Delete,objectName=filePath,absolutePath=app_offline\.htm 
# -skip:skipAction=Delete,objectName=filePath,absolutePath=App_Data[\\].* 
# -skip:skipAction=Delete,objectName=dirPath,absolutePath="\\App_Data" 
# -skip:skipAction=Delete,objectName=filePath,absolutePath=media[\\].* 
# -skip:skipAction=Delete,objectName=dirPath,absolutePath="\\media" 
# -skip:skipAction=Delete,objectName=filePath,absolutePath="\\App_Plugins\\UmbracoForms\\Data\\*.*" 
# -skip:skipAction=Delete,objectName=filePath,absolutePath="\\App_Plugins\\UmbracoForms\\Data\\forms\\*.*" 
# -skip:skipAction=Delete,objectName=filePath,absolutePath="\\App_Plugins\\UmbracoForms\\Data\\Templates\\*.*" 
# -skip:skipAction=Delete,objectName=filePath,absolutePath="\\App_Plugins\\UmbracoForms\\Data\\Workflows\\*.*"

# s:"${bamboo.Solution}.Web\Web.config" 
# t:"${bamboo.Solution}.Web\Web.${bamboo.BuildConfiguration}.config" 
# d:"${bamboo.Solution}.Web\Web.config" pw