name: 'Build .NET'
description: 'Build .NET for Umbraco V8'
inputs:
  organization-name:
    required: true
  project-name:
    required: true
  build-configuration:
    required: true
    default: 'release'
  csproj-path:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name : Setup Nuget
      uses: nuget/setup-nuget@v1.0.6

    - name: Restore nuget packages
      run: nuget restore ${{ inputs.csproj-path }}
      shell: powershell

    - name: Stop AppPool and Website in IIS
      run: c:\.\DeploymentScripts\StopIISAppPool.ps1 "${{ inputs.organization-name }} ${{ inputs.project-name }} (${{ github.ref_name }})"
      shell: powershell

    - name: Transform web.config
      run: |
        cd .\*.web\
        c:\.\DeploymentScripts\ConfigTransformationTool\ctt.exe s:web.config t:web.bamboo.config d:web.config pw
      shell: powershell

    - name: Build Solution
      run: msbuild Axendo.Umb.DataExpert.Platform.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:AutoParameterizationWebConfigConnectionStrings=false /p:MvcBuildViews=false
      shell: powershell
    
    # copy files to sites folder
    - name: Copy files to sites folder
      run: |
        mkdir C:\Sites\DataExpert\Platform\master
        Copy-Item .\*.Web\* C:\Sites\DataExpert\Platform\master -force -recurse -verbose
      shell: powershell
    
    # create robots.txt (disallow all)

    - name: Create AppPool and Website in IIS
      run: C:\.\DeploymentScripts\CreateIISAppPoolAndWebsite.ps1 "${{ inputs.organization-name }} ${{ inputs.project-name }} (${{ github.ref_name }})" "${{ github.ref_name }}.${{ inputs.project-name }}.${{ inputs.organization-name }}" "C:\Sites\${{ inputs.organization-name }}\${{ inputs.project-name }}\${{ github.ref_name }}" "v4.0"
      shell: powershell
